// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzrXodw5PmOUNgyo_SJ7hPQsAhBpiZcnk',
    appId: '1:1033930402349:web:XXXXXXXXXXXXXXX',
    messagingSenderId: '1033930402349',
    projectId: 'petmach-2596f',
    authDomain: 'petmach-2596f.firebaseapp.com',
    storageBucket: 'petmach-2596f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrXodw5PmOUNgyo_SJ7hPQsAhBpiZcnk',
    appId: '1:1033930402349:android:b759dfa79748c23d0a66a4',
    messagingSenderId: '1033930402349',
    projectId: 'petmach-2596f',
    storageBucket: 'petmach-2596f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMnoE1yJAeV4IsN4PiBKk1N4ZGHIezvOk',
    appId: '1:610643579092:web:69090edf50a0c70f87eb41',
    messagingSenderId: '610643579092',
    projectId: 'petmatch-1004e',
    authDomain: 'petmatch-1004e.firebaseapp.com',
    storageBucket: 'petmatch-1004e.firebasestorage.app',
  );
}
